name: CI for Weather App

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPEN_WEATHER_API_KEY: ${{  secrets.OPEN_WEATHER_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install dependencies
        run: composer install

      - name: Create .env file
        run: |
          echo "OPEN_WEATHER_API_KEY=${{ secrets.OPEN_WEATHER_API_KEY }}" > .env

      - name: Run PHP lint
        run: |
          find . -type f -name "*.php" -not -path "./vendor/*" xargs -I {} php -l {} \;

          - name: run tests
          run: php tests/weatherTest.php
